#!/usr/bin/env python3
"""Generate run manifest, all-package summary, and crash clusters for a workspace."""
import argparse
import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path


SUMMARY_DIR_NAME = "6.总结报告"


def parse_args():
    parser = argparse.ArgumentParser(description="Generate workspace-level coredump analysis summaries")
    parser.add_argument("--workspace", required=True)
    parser.add_argument("--packages", help="Comma separated package list")
    parser.add_argument("--date-range-label", default="")
    parser.add_argument("--status-file", help="Package status TSV generated by run_analysis_agent.sh")
    parser.add_argument("--version-status-file", help="Version status TSV generated by analyze_crash_complete.sh")
    parser.add_argument("--failed-packages", default="", help="Comma separated failed package list")
    parser.add_argument("--list-failed", action="store_true", help="Print packages that should be retried")
    return parser.parse_args()


def read_json(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def split_packages(value):
    return [p.strip() for p in (value or "").split(",") if p.strip()]


def load_run_context(summary_dir):
    return read_json(summary_dir / "run_context.json") or {}


def latest_status_by_package(status_file):
    statuses = {}
    if not status_file:
        return statuses
    path = Path(status_file)
    if not path.exists():
        return statuses
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t", 4)
            if len(parts) < 4:
                continue
            timestamp, package, status, exit_code = parts[:4]
            message = parts[4] if len(parts) > 4 else ""
            statuses[package] = {
                "timestamp": timestamp,
                "status": status,
                "exit_code": exit_code,
                "message": message,
            }
    return statuses


def load_version_status(version_status_file):
    result = defaultdict(list)
    if not version_status_file:
        return result
    path = Path(version_status_file)
    if not path.exists():
        return result
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t", 5)
            if len(parts) < 5:
                continue
            timestamp, package, version, step, status = parts[:5]
            message = parts[5] if len(parts) > 5 else ""
            result[package].append({
                "timestamp": timestamp,
                "version": version,
                "step": step,
                "status": status,
                "message": message,
            })
    return result


def discover_packages(workspace, requested):
    packages = set(requested)
    for stats in (workspace / "2.数据筛选").glob("*_crash_statistics.json"):
        packages.add(stats.name.replace("_crash_statistics.json", ""))
    analysis_root = workspace / "5.崩溃分析"
    if analysis_root.exists():
        for child in analysis_root.iterdir():
            if child.is_dir():
                packages.add(child.name)
    return sorted(packages)


def stats_summary(workspace, package):
    stats_path = workspace / "2.数据筛选" / f"{package}_crash_statistics.json"
    data = read_json(stats_path) or {}
    summary = data.get("summary", {})
    return stats_path, {
        "total_records": int(summary.get("total_records", 0) or 0),
        "valid_records": int(summary.get("valid_records", 0) or 0),
        "unique_crashes": int(summary.get("unique_crashes", 0) or 0),
        "duplicate_crashes": int(summary.get("duplicate_crashes", 0) or 0),
        "versions_count": int(summary.get("versions_count", 0) or 0),
        "analysis_time": summary.get("analysis_time", ""),
        "by_signal": data.get("by_signal", {}),
        "by_version": data.get("by_version", {}),
    }


def report_paths(workspace, package):
    analysis_dir = workspace / "5.崩溃分析" / package
    summary_dir = workspace / SUMMARY_DIR_NAME
    return {
        "analysis_dir": str(analysis_dir),
        "full_analysis_report": str(analysis_dir / "full_analysis_report.md"),
        "ai_analysis_report": str(analysis_dir / "AI_analysis_report.md"),
        "package_final_conclusion": str(summary_dir / "final_conclusion.md"),
        "package_summary_statistics": str(summary_dir / "summary_statistics.json"),
    }


def infer_package_status(stats, analysis_count, source_available, full_report, ai_report, event):
    if event and event.get("status") == "failed":
        return "failed"
    if event and event.get("status") == "running":
        return "running"
    if event and event.get("status") == "skipped_completed":
        return "skipped_completed"

    if stats["valid_records"] == 0 and (full_report.exists() or ai_report.exists()):
        return "completed_no_data"
    if full_report.exists() and ai_report.exists():
        if stats["valid_records"] > 0 and stats["versions_count"] > 0 and not source_available:
            return "completed_data_only"
        if stats["versions_count"] > 0 and analysis_count < stats["versions_count"]:
            return "partial"
        return "completed"
    if stats["valid_records"] > 0 or analysis_count > 0:
        return "partial"
    return "pending"


def package_entry(workspace, package, event, version_events):
    stats_path, stats = stats_summary(workspace, package)
    paths = report_paths(workspace, package)
    analysis_dir = Path(paths["analysis_dir"])
    version_dirs = list(analysis_dir.glob("version_*")) if analysis_dir.exists() else []
    analysis_count = sum(1 for d in version_dirs if (d / "analysis.json").exists())
    source_available = (workspace / "3.代码管理" / package / ".git").exists()
    deb_count = len(list((workspace / "4.包管理" / "downloads").glob(f"{package}*.deb")))
    full_report = Path(paths["full_analysis_report"])
    ai_report = Path(paths["ai_analysis_report"])

    source_failures = sum(1 for e in version_events if e["step"] == "source" and e["status"] != "ok")
    package_skips = sum(1 for e in version_events if e["step"] == "package" and e["status"].startswith("skipped"))
    package_failures = sum(1 for e in version_events if e["step"] == "package" and e["status"].startswith("failed"))
    analysis_failures = sum(1 for e in version_events if e["step"] == "analysis" and e["status"] != "ok")

    status = infer_package_status(stats, analysis_count, source_available, full_report, ai_report, event)
    return {
        "package": package,
        "status": status,
        "last_event": event or {},
        "statistics_file": str(stats_path),
        "total_records": stats["total_records"],
        "valid_records": stats["valid_records"],
        "unique_crashes": stats["unique_crashes"],
        "duplicate_crashes": stats["duplicate_crashes"],
        "versions_count": stats["versions_count"],
        "analyzed_versions": analysis_count,
        "source_available": source_available,
        "source_failures": source_failures,
        "package_skips": package_skips,
        "package_failures": package_failures,
        "analysis_failures": analysis_failures,
        "downloaded_deb_files": deb_count,
        "reports": {
            "full_analysis_report_exists": full_report.exists(),
            "ai_analysis_report_exists": ai_report.exists(),
            **paths,
        },
    }


def categorize_root_cause(text):
    lower = text.lower()
    if any(x in lower for x in ("dbus", "qdbus", "pendingcall", "watcher")):
        return "D-Bus连接/回调生命周期"
    if any(x in lower for x in ("xcb", "x11", "display", "qxcb")):
        return "X11/XCB连接"
    if any(x in lower for x in ("qobject", "qwidget", "postevent", "event", "delete", "destroy", "d1ev", "d0ev")):
        return "Qt对象生命周期/事件循环"
    if any(x in lower for x in ("thread", "qtconcurrent", "runfunctiontask", "pthread")):
        return "线程/并发访问"
    if any(x in lower for x in ("assert", "abort", "raise", "sigabrt")):
        return "断言/主动终止"
    if any(x in lower for x in ("null", "segv", "sigsegv", "invalid", "pointer")):
        return "内存访问/空指针"
    return "待人工判断"


def crash_key(crash):
    symbol = crash.get("app_layer_symbol") or ""
    key_frame = crash.get("key_frame") or {}
    if not symbol:
        symbol = key_frame.get("symbol") or ""
    if not symbol:
        frames = crash.get("frames") or []
        if frames:
            symbol = frames[0].get("symbol", "")
    if not symbol:
        symbol = "unknown"
    symbol = re.sub(r"\s+", " ", symbol).strip()
    signal = crash.get("signal") or "UNKNOWN"
    library = crash.get("app_layer_library") or key_frame.get("library") or ""
    return f"{signal}|{library}|{symbol}"


def collect_clusters(workspace, packages):
    clusters = {}
    for package in packages:
        for analysis_file in sorted((workspace / "5.崩溃分析" / package).glob("version_*/analysis.json")):
            data = read_json(analysis_file) or {}
            version = data.get("version") or analysis_file.parent.name.replace("version_", "").replace("_", ".")
            for crash in data.get("crashes", []):
                key = crash_key(crash)
                count = int(crash.get("count", 1) or 1)
                text = " ".join([
                    key,
                    crash.get("description", ""),
                    crash.get("fix_reason", ""),
                    crash.get("stack_info", "")[:500],
                ])
                item = clusters.setdefault(key, {
                    "cluster_id": f"C{len(clusters) + 1:04d}",
                    "key": key,
                    "root_cause_category": categorize_root_cause(text),
                    "total_count": 0,
                    "unique_crashes": 0,
                    "packages": set(),
                    "versions": set(),
                    "signals": set(),
                    "example": crash,
                })
                item["total_count"] += count
                item["unique_crashes"] += 1
                item["packages"].add(package)
                item["versions"].add(f"{package}:{version}")
                item["signals"].add(crash.get("signal") or "UNKNOWN")

    result = []
    for item in clusters.values():
        item["packages"] = sorted(item["packages"])
        item["versions"] = sorted(item["versions"])
        item["signals"] = sorted(item["signals"])
        result.append(item)
    result.sort(key=lambda x: (-x["total_count"], -x["unique_crashes"], x["key"]))
    return result


def clean_version_label(value):
    value = (value or "").strip()
    if not value:
        return ""
    if ":" in value:
        value = value.split(":", 1)[1]
    value = re.sub(r"-1$", "", value)
    return value


def load_expected_versions(workspace, package):
    path = workspace / "2.数据筛选" / f"{package}_crash_versions.txt"
    versions = []
    if not path.exists():
        return versions
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            rest = line.rsplit(":", 1)[0]
            versions.append(clean_version_label(rest))
    return versions


def build_retry_targets(workspace, manifest, version_statuses, run_context):
    retry_package_statuses = {"failed", "partial", "running", "pending"}
    retry_packages = []
    retry_versions = []

    for entry in manifest["packages"]:
        package = entry["package"]
        if entry["status"] in retry_package_statuses:
            retry_packages.append(package)

        events = version_statuses.get(package, [])
        by_version = defaultdict(list)
        for event in events:
            version = clean_version_label(event.get("version", ""))
            if version:
                by_version[version].append(event)

        expected_versions = load_expected_versions(workspace, package)
        for version in expected_versions:
            version_events = by_version.get(version, [])
            step_status = {e["step"]: e["status"] for e in version_events}
            failed_steps = [e["step"] for e in version_events if e["status"] not in ("ok", "skipped_no_sudo")]
            last_message = version_events[-1]["message"] if version_events else "no execution record"
            needs_retry = False

            if not version_events:
                needs_retry = True
                failed_steps = ["missing"]
            elif step_status.get("analysis") != "ok":
                needs_retry = True
            elif step_status.get("source", "").startswith("failed"):
                needs_retry = True
            elif any(status.startswith("failed") for status in step_status.values()):
                needs_retry = True

            if needs_retry:
                retry_strategy, step_retry_command = build_step_retry_strategy(
                    package, version, failed_steps, workspace, run_context
                )
                retry_versions.append({
                    "package": package,
                    "version": version,
                    "failed_steps": failed_steps,
                    "last_message": last_message,
                    "command": build_retry_command(package, workspace, run_context, version),
                    "retry_strategy": retry_strategy,
                    "step_command": step_retry_command,
                })

    retry_packages = sorted(set(retry_packages))
    retry_versions.sort(key=lambda x: (x["package"], x["version"]))
    return retry_packages, retry_versions


def build_retry_command(package, workspace, run_context, version=None):
    parts = [
        "bash coredump-full-analysis/scripts/analyze_crash_complete.sh" if version else "bash run_analysis_agent.sh",
        f"--package {package}" if version else f"--packages {package}",
        f"--workspace {workspace}",
    ]
    arch = run_context.get("arch", "")
    sys_version = run_context.get("sys_version", "")
    start_date = run_context.get("start_date", "")
    end_date = run_context.get("end_date", "")
    if arch:
        parts.append(f"--arch {arch}")
    if sys_version:
        parts.append(f"--sys-version {sys_version}")
    if start_date:
        parts.append(f"--start-date {start_date}")
    if end_date:
        parts.append(f"--end-date {end_date}")
    if version:
        parts.append(f"--versions {version}")
    return " ".join(parts)


def build_retry_step_command(package, version, workspace, run_context, strategy):
    parts = [
        "bash coredump-full-analysis/scripts/run_retry_step.sh",
        f"--package {package}",
        f"--version {version}",
        f"--workspace {workspace}",
        f"--strategy {strategy}",
    ]
    arch = run_context.get("arch", "")
    sys_version = run_context.get("sys_version", "")
    start_date = run_context.get("start_date", "")
    end_date = run_context.get("end_date", "")
    if arch:
        parts.append(f"--arch {arch}")
    if sys_version:
        parts.append(f"--sys-version {sys_version}")
    if start_date:
        parts.append(f"--start-date {start_date}")
    if end_date:
        parts.append(f"--end-date {end_date}")
    return " ".join(parts)


def build_step_retry_strategy(package, version, failed_steps, workspace, run_context):
    normalized_steps = [step for step in failed_steps if step]
    if "missing" in normalized_steps or "source" in normalized_steps:
        return "full_version_rerun", build_retry_step_command(package, version, workspace, run_context, "full_version_rerun")

    if not normalized_steps:
        return "full_version_rerun", build_retry_step_command(package, version, workspace, run_context, "full_version_rerun")

    if normalized_steps == ["analysis"]:
        return "analysis_only", build_retry_step_command(package, version, workspace, run_context, "analysis_only")

    if set(normalized_steps).issubset({"package", "analysis"}):
        return "package_then_analysis", build_retry_step_command(package, version, workspace, run_context, "package_then_analysis")

    return "full_version_rerun", build_retry_step_command(package, version, workspace, run_context, "full_version_rerun")


def generate_manifest(workspace, packages, package_statuses, version_statuses, date_range_label):
    entries = [
        package_entry(workspace, package, package_statuses.get(package), version_statuses.get(package, []))
        for package in packages
    ]
    totals = {
        "packages": len(entries),
        "completed": sum(1 for e in entries if e["status"] in ("completed", "completed_no_data", "completed_data_only", "skipped_completed")),
        "failed": sum(1 for e in entries if e["status"] == "failed"),
        "partial": sum(1 for e in entries if e["status"] == "partial"),
        "pending": sum(1 for e in entries if e["status"] == "pending"),
        "valid_records": sum(e["valid_records"] for e in entries),
        "unique_crashes": sum(e["unique_crashes"] for e in entries),
        "versions": sum(e["versions_count"] for e in entries),
        "analyzed_versions": sum(e["analyzed_versions"] for e in entries),
    }
    return {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "workspace": str(workspace),
        "summary_dir": str(workspace / SUMMARY_DIR_NAME),
        "date_range": date_range_label,
        "totals": totals,
        "packages": entries,
    }


def write_manifest_md(path, manifest):
    lines = [
        "# 运行 Manifest\n\n",
        f"**生成时间**: {manifest['generated_at']}\n\n",
        f"**工作目录**: `{manifest['workspace']}`\n\n",
    ]
    if manifest.get("date_range"):
        lines.append(f"**日期范围**: {manifest['date_range']}\n\n")
    totals = manifest["totals"]
    lines.extend([
        "## 总体状态\n\n",
        f"- 包数量: {totals['packages']}\n",
        f"- 完成: {totals['completed']}\n",
        f"- 失败: {totals['failed']}\n",
        f"- 部分完成: {totals['partial']}\n",
        f"- 待处理: {totals['pending']}\n",
        f"- 有效记录: {totals['valid_records']}\n",
        f"- 唯一崩溃: {totals['unique_crashes']}\n",
        f"- 版本数: {totals['versions']}\n",
        f"- 已分析版本: {totals['analyzed_versions']}\n\n",
        "## 包状态\n\n",
        "| 包 | 状态 | 有效记录 | 唯一崩溃 | 版本 | 已分析版本 | 源码 | 源码失败 | 包跳过 | 报告 |\n",
        "|----|------|----------|----------|------|------------|------|----------|--------|------|\n",
    ])
    for entry in manifest["packages"]:
        reports_ok = "yes" if entry["reports"]["ai_analysis_report_exists"] else "no"
        source = "yes" if entry["source_available"] else "no"
        lines.append(
            f"| {entry['package']} | {entry['status']} | {entry['valid_records']} | "
            f"{entry['unique_crashes']} | {entry['versions_count']} | {entry['analyzed_versions']} | "
            f"{source} | {entry['source_failures']} | {entry['package_skips']} | {reports_ok} |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_all_summary(path, manifest):
    lines = [
        "# 全包崩溃分析汇总\n\n",
        f"**生成时间**: {manifest['generated_at']}\n\n",
        f"**工作目录**: `{manifest['workspace']}`\n\n",
    ]
    if manifest.get("date_range"):
        lines.append(f"**日期范围**: {manifest['date_range']}\n\n")
    totals = manifest["totals"]
    lines.extend([
        "## 总览\n\n",
        f"- 包数量: {totals['packages']}\n",
        f"- 有效崩溃记录: {totals['valid_records']}\n",
        f"- 唯一崩溃: {totals['unique_crashes']}\n",
        f"- 版本数: {totals['versions']}\n",
        f"- 已分析版本: {totals['analyzed_versions']}\n\n",
        "## Top 包\n\n",
        "| 包 | 状态 | 有效记录 | 唯一崩溃 | 版本数 | 报告 |\n",
        "|----|------|----------|----------|--------|------|\n",
    ])
    ranked = sorted(manifest["packages"], key=lambda e: (-e["unique_crashes"], -e["valid_records"], e["package"]))
    for entry in ranked:
        report = entry["reports"]["ai_analysis_report"]
        lines.append(
            f"| {entry['package']} | {entry['status']} | {entry['valid_records']} | "
            f"{entry['unique_crashes']} | {entry['versions_count']} | `{report}` |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_cluster_md(path, clusters):
    lines = [
        "# 跨包问题簇汇总\n\n",
        f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n",
        f"**问题簇数量**: {len(clusters)}\n\n",
        "| ID | 类别 | 总次数 | 唯一崩溃 | 包 | 信号 | 关键符号 |\n",
        "|----|------|--------|----------|----|------|----------|\n",
    ]
    for cluster in clusters[:80]:
        key_symbol = cluster["key"].split("|")[-1]
        lines.append(
            f"| {cluster['cluster_id']} | {cluster['root_cause_category']} | {cluster['total_count']} | "
            f"{cluster['unique_crashes']} | {', '.join(cluster['packages'][:5])} | "
            f"{', '.join(cluster['signals'])} | `{key_symbol}` |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_packages(path, retry_packages):
    lines = ["# 需要重跑的包\n"]
    for package in retry_packages:
        lines.append(f"{package}\n")
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_versions_tsv(path, retry_versions):
    lines = ["package\tversion\tfailed_steps\tretry_strategy\tlast_message\tcommand\tstep_command\n"]
    for item in retry_versions:
        lines.append(
            f"{item['package']}\t{item['version']}\t{','.join(item['failed_steps'])}\t"
            f"{item['retry_strategy']}\t{item['last_message']}\t{item['command']}\t{item['step_command']}\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_versions_md(path, retry_versions):
    lines = [
        "# 需要重跑的版本\n\n",
        f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n",
        "| 包 | 版本 | 失败步骤 | 重跑策略 | 说明 | 重跑命令 |\n",
        "|----|------|----------|----------|------|----------|\n",
    ]
    for item in retry_versions:
        lines.append(
            f"| {item['package']} | {item['version']} | {', '.join(item['failed_steps'])} | {item['retry_strategy']} | "
            f"{item['last_message']} | `{item['command']}` |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_commands(path, workspace, retry_packages, run_context):
    summary_dir_literal = json.dumps(str(workspace / SUMMARY_DIR_NAME), ensure_ascii=False)
    lines = [
        "#!/bin/bash\n",
        "set -e\n\n",
        f"WORKSPACE={json.dumps(str(workspace))}\n\n",
        f"SUMMARY_DIR={summary_dir_literal}\n\n",
    ]
    for package in retry_packages:
        command = build_retry_command(package, "$WORKSPACE", run_context)
        lines.append(f"{command}\n")
    lines.extend(build_summary_refresh_block(run_context))
    if retry_packages:
        lines.extend([
            "\n# 校验包级重跑结果\n",
            "python3 coredump-full-analysis/scripts/verify_retry_targets.py \\\n",
            "  --summary-dir \"$SUMMARY_DIR\" \\\n",
            f"  --packages {json.dumps(','.join(retry_packages), ensure_ascii=False)}\n",
        ])
    path.write_text("".join(lines), encoding="utf-8")
    path.chmod(0o755)


def write_retry_version_commands(path, workspace, retry_versions, run_context):
    summary_dir_literal = json.dumps(str(workspace / SUMMARY_DIR_NAME), ensure_ascii=False)
    lines = [
        "#!/bin/bash\n",
        "set -e\n\n",
        f"WORKSPACE={json.dumps(str(workspace))}\n\n",
        f"SUMMARY_DIR={summary_dir_literal}\n",
        "TARGET_VERSIONS_FILE=\"$SUMMARY_DIR/.retry_versions_targets.tsv\"\n\n",
    ]
    if retry_versions:
        lines.append("cat > \"$TARGET_VERSIONS_FILE\" <<'EOF'\n")
        for item in retry_versions:
            lines.append(f"{item['package']}\t{item['version']}\n")
        lines.append("EOF\n\n")
    for item in retry_versions:
        command = build_retry_command(item["package"], "$WORKSPACE", run_context, item["version"])
        lines.append(f"{command}\n")
    lines.extend(build_summary_refresh_block(run_context))
    if retry_versions:
        lines.extend([
            "\n# 校验版本级重跑结果\n",
            "python3 coredump-full-analysis/scripts/verify_retry_targets.py \\\n",
            "  --summary-dir \"$SUMMARY_DIR\" \\\n",
            "  --versions-file \"$TARGET_VERSIONS_FILE\"\n",
        ])
    path.write_text("".join(lines), encoding="utf-8")
    path.chmod(0o755)


def write_retry_failed_step_commands(path, workspace, retry_versions, run_context):
    summary_dir_literal = json.dumps(str(workspace / SUMMARY_DIR_NAME), ensure_ascii=False)
    lines = [
        "#!/bin/bash\n",
        "set -e\n\n",
        f"WORKSPACE={json.dumps(str(workspace))}\n\n",
        f"SUMMARY_DIR={summary_dir_literal}\n",
        "TARGET_VERSIONS_FILE=\"$SUMMARY_DIR/.retry_failed_step_targets.tsv\"\n\n",
    ]
    if retry_versions:
        lines.append("cat > \"$TARGET_VERSIONS_FILE\" <<'EOF'\n")
        for item in retry_versions:
            lines.append(f"{item['package']}\t{item['version']}\n")
        lines.append("EOF\n\n")
    for item in retry_versions:
        command = item.get("step_command", "")
        if not command:
            continue
        command = command.replace(str(workspace), "$WORKSPACE")
        lines.append(f"# {item['package']} {item['version']} [{item['retry_strategy']}]\n")
        lines.append(f"{command}\n\n")
    lines.extend(build_summary_refresh_block(run_context))
    if retry_versions:
        lines.extend([
            "\n# 校验失败步骤重跑结果\n",
            "python3 coredump-full-analysis/scripts/verify_retry_targets.py \\\n",
            "  --summary-dir \"$SUMMARY_DIR\" \\\n",
            "  --versions-file \"$TARGET_VERSIONS_FILE\"\n",
        ])
    path.write_text("".join(lines), encoding="utf-8")
    path.chmod(0o755)


def build_summary_refresh_block(run_context):
    packages = run_context.get("packages", "")
    date_range_label = run_context.get("date_range_label", "")
    packages_arg = json.dumps(packages, ensure_ascii=False)
    date_range_arg = json.dumps(date_range_label, ensure_ascii=False)
    return [
        "\n# 刷新 workspace 汇总\n",
        "python3 coredump-full-analysis/scripts/generate_workspace_summary.py \\\n",
        "  --workspace \"$WORKSPACE\" \\\n",
        f"  --packages {packages_arg} \\\n",
        f"  --date-range-label {date_range_arg}\n",
    ]


def write_retry_summary_md(path, manifest, retry_packages, retry_versions):
    package_map = {entry["package"]: entry for entry in manifest["packages"]}
    retry_by_package = defaultdict(list)
    for item in retry_versions:
        retry_by_package[item["package"]].append(item)

    lines = [
        "# 重跑摘要\n\n",
        f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n",
        f"- 需要重跑的包: {len(retry_packages)}\n",
        f"- 需要重跑的版本: {len(retry_versions)}\n\n",
    ]

    if retry_packages:
        lines.extend([
            "## 包级重跑\n\n",
            "| 包 | 当前状态 | 最近结果 | 有效记录 | 唯一崩溃 | 说明 |\n",
            "|----|----------|----------|----------|----------|------|\n",
        ])
        for package in retry_packages:
            entry = package_map.get(package, {})
            last_event = entry.get("last_event", {}) if entry else {}
            message = last_event.get("message", "") or "reported by manifest"
            lines.append(
                f"| {package} | {entry.get('status', 'unknown')} | {last_event.get('status', 'unknown')} | "
                f"{entry.get('valid_records', 0)} | {entry.get('unique_crashes', 0)} | {message} |\n"
            )
        lines.append("\n")

    if retry_versions:
        lines.extend([
            "## 版本级重跑\n\n",
            "| 包 | 版本 | 失败步骤 | 最后信息 |\n",
            "|----|------|----------|----------|\n",
        ])
        for item in retry_versions:
            lines.append(
                f"| {item['package']} | {item['version']} | {', '.join(item['failed_steps'])} | "
                f"{item['last_message']} |\n"
            )
        lines.append("\n")

        lines.append("## 按包汇总\n\n")
        for package in sorted(retry_by_package):
            lines.append(f"### {package}\n\n")
            for item in retry_by_package[package]:
                lines.append(
                    f"- 版本 `{item['version']}`: 步骤 `{', '.join(item['failed_steps'])}`; "
                    f"策略 `{item['retry_strategy']}`; {item['last_message']}\n"
                )
            lines.append("\n")
    else:
        lines.append("## 版本级重跑\n\n当前没有需要精确重跑的版本。\n")

    lines.extend([
        "## 相关文件\n\n",
        f"- `retry_packages.txt`\n",
        f"- `retry_versions.tsv`\n",
        f"- `retry_commands.sh`\n",
        f"- `retry_versions.sh`\n",
        f"- `retry_failed_steps.sh`\n",
        f"- `validate_workspace_retry_closure.py`\n",
        f"- `validate_workspace.sh`\n",
    ])
    path.write_text("".join(lines), encoding="utf-8")


def main():
    args = parse_args()
    workspace = Path(args.workspace)
    summary_dir = workspace / SUMMARY_DIR_NAME
    summary_dir.mkdir(parents=True, exist_ok=True)
    run_context = load_run_context(summary_dir)

    requested = split_packages(args.packages)
    packages = discover_packages(workspace, requested)
    package_statuses = latest_status_by_package(args.status_file or str(summary_dir / "package_status.tsv"))
    version_statuses = load_version_status(args.version_status_file or str(summary_dir / "version_status.tsv"))

    for pkg in split_packages(args.failed_packages):
        package_statuses[pkg] = {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "status": "failed",
            "exit_code": "1",
            "message": "reported by caller",
        }

    manifest = generate_manifest(workspace, packages, package_statuses, version_statuses, args.date_range_label)
    clusters = collect_clusters(workspace, packages)
    retry_packages, retry_versions = build_retry_targets(workspace, manifest, version_statuses, run_context)

    if args.list_failed:
        retry_statuses = {"failed", "partial", "running", "pending"}
        for entry in manifest["packages"]:
            if entry["status"] in retry_statuses:
                print(entry["package"])
        return

    write_json(summary_dir / "run_manifest.json", manifest)
    write_manifest_md(summary_dir / "run_manifest.md", manifest)
    write_json(summary_dir / "all_packages_summary.json", {
        "generated_at": manifest["generated_at"],
        "workspace": manifest["workspace"],
        "date_range": manifest["date_range"],
        "totals": manifest["totals"],
        "packages": manifest["packages"],
    })
    write_all_summary(summary_dir / "all_packages_summary.md", manifest)
    write_json(summary_dir / "root_cause_clusters.json", clusters)
    write_cluster_md(summary_dir / "root_cause_clusters.md", clusters)
    write_retry_packages(summary_dir / "retry_packages.txt", retry_packages)
    write_json(summary_dir / "retry_versions.json", retry_versions)
    write_retry_versions_tsv(summary_dir / "retry_versions.tsv", retry_versions)
    write_retry_versions_md(summary_dir / "retry_versions.md", retry_versions)
    write_retry_commands(summary_dir / "retry_commands.sh", workspace, retry_packages, run_context)
    write_retry_version_commands(summary_dir / "retry_versions.sh", workspace, retry_versions, run_context)
    write_retry_failed_step_commands(summary_dir / "retry_failed_steps.sh", workspace, retry_versions, run_context)
    write_retry_summary_md(summary_dir / "retry_summary.md", manifest, retry_packages, retry_versions)

    print(f"✅ run_manifest.md 已生成: {summary_dir / 'run_manifest.md'}")
    print(f"✅ all_packages_summary.md 已生成: {summary_dir / 'all_packages_summary.md'}")
    print(f"✅ root_cause_clusters.md 已生成: {summary_dir / 'root_cause_clusters.md'}")
    print(f"✅ retry_packages.txt 已生成: {summary_dir / 'retry_packages.txt'}")
    print(f"✅ retry_versions.md 已生成: {summary_dir / 'retry_versions.md'}")
    print(f"✅ retry_versions.sh 已生成: {summary_dir / 'retry_versions.sh'}")
    print(f"✅ retry_failed_steps.sh 已生成: {summary_dir / 'retry_failed_steps.sh'}")
    print(f"✅ retry_summary.md 已生成: {summary_dir / 'retry_summary.md'}")


if __name__ == "__main__":
    main()
