#!/usr/bin/env python3
"""Generate run manifest, all-package summary, and crash clusters for a workspace."""
import argparse
import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path


SUMMARY_DIR_NAME = "6.总结报告"


def parse_args():
    parser = argparse.ArgumentParser(description="Generate workspace-level coredump analysis summaries")
    parser.add_argument("--workspace", required=True)
    parser.add_argument("--packages", help="Comma separated package list")
    parser.add_argument("--date-range-label", default="")
    parser.add_argument("--status-file", help="Package status TSV generated by run_analysis_agent.sh")
    parser.add_argument("--version-status-file", help="Version status TSV generated by analyze_crash_complete.sh")
    parser.add_argument("--failed-packages", default="", help="Comma separated failed package list")
    parser.add_argument("--list-failed", action="store_true", help="Print packages that should be retried")
    return parser.parse_args()


def read_json(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def split_packages(value):
    return [p.strip() for p in (value or "").split(",") if p.strip()]


def load_run_context(summary_dir):
    return read_json(summary_dir / "run_context.json") or {}


def latest_status_by_package(status_file):
    statuses = {}
    if not status_file:
        return statuses
    path = Path(status_file)
    if not path.exists():
        return statuses
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t", 4)
            if len(parts) < 4:
                continue
            timestamp, package, status, exit_code = parts[:4]
            message = parts[4] if len(parts) > 4 else ""
            statuses[package] = {
                "timestamp": timestamp,
                "status": status,
                "exit_code": exit_code,
                "message": message,
            }
    return statuses


def load_version_status(version_status_file):
    result = defaultdict(list)
    if not version_status_file:
        return result
    path = Path(version_status_file)
    if not path.exists():
        return result
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t", 5)
            if len(parts) < 5:
                continue
            timestamp, package, version, step, status = parts[:5]
            message = parts[5] if len(parts) > 5 else ""
            result[package].append({
                "timestamp": timestamp,
                "version": version,
                "step": step,
                "status": status,
                "message": message,
            })
    return result


def discover_packages(workspace, requested):
    packages = set(requested)
    for stats in (workspace / "2.数据筛选").glob("*_crash_statistics.json"):
        packages.add(stats.name.replace("_crash_statistics.json", ""))
    analysis_root = workspace / "5.崩溃分析"
    if analysis_root.exists():
        for child in analysis_root.iterdir():
            if child.is_dir():
                packages.add(child.name)
    return sorted(packages)


def stats_summary(workspace, package):
    stats_path = workspace / "2.数据筛选" / f"{package}_crash_statistics.json"
    data = read_json(stats_path) or {}
    summary = data.get("summary", {})
    return stats_path, {
        "total_records": int(summary.get("total_records", 0) or 0),
        "valid_records": int(summary.get("valid_records", 0) or 0),
        "unique_crashes": int(summary.get("unique_crashes", 0) or 0),
        "duplicate_crashes": int(summary.get("duplicate_crashes", 0) or 0),
        "versions_count": int(summary.get("versions_count", 0) or 0),
        "analysis_time": summary.get("analysis_time", ""),
        "by_signal": data.get("by_signal", {}),
        "by_version": data.get("by_version", {}),
    }


def report_paths(workspace, package):
    analysis_dir = workspace / "5.崩溃分析" / package
    summary_dir = workspace / SUMMARY_DIR_NAME
    return {
        "analysis_dir": str(analysis_dir),
        "full_analysis_report": str(analysis_dir / "full_analysis_report.md"),
        "ai_analysis_report": str(analysis_dir / "AI_analysis_report.md"),
        "package_final_conclusion": str(summary_dir / "final_conclusion.md"),
        "package_summary_statistics": str(summary_dir / "summary_statistics.json"),
    }


def infer_package_status(stats, analysis_count, source_available, full_report, ai_report, event):
    if event and event.get("status") == "failed":
        return "failed"
    if event and event.get("status") == "running":
        return "running"
    if event and event.get("status") == "skipped_completed":
        return "skipped_completed"

    if stats["valid_records"] == 0 and (full_report.exists() or ai_report.exists()):
        return "completed_no_data"
    if full_report.exists() and ai_report.exists():
        if stats["valid_records"] > 0 and stats["versions_count"] > 0 and not source_available:
            return "completed_data_only"
        if stats["versions_count"] > 0 and analysis_count < stats["versions_count"]:
            return "partial"
        return "completed"
    if stats["valid_records"] > 0 or analysis_count > 0:
        return "partial"
    return "pending"


def package_entry(workspace, package, event, version_events):
    stats_path, stats = stats_summary(workspace, package)
    paths = report_paths(workspace, package)
    analysis_dir = Path(paths["analysis_dir"])
    version_dirs = list(analysis_dir.glob("version_*")) if analysis_dir.exists() else []
    analysis_count = sum(1 for d in version_dirs if (d / "analysis.json").exists())
    source_available = (workspace / "3.代码管理" / package / ".git").exists()
    deb_count = len(list((workspace / "4.包管理" / "downloads").glob(f"{package}*.deb")))
    full_report = Path(paths["full_analysis_report"])
    ai_report = Path(paths["ai_analysis_report"])

    source_failures = sum(1 for e in version_events if e["step"] == "source" and e["status"] != "ok")
    package_skips = sum(1 for e in version_events if e["step"] == "package" and e["status"].startswith("skipped"))
    package_failures = sum(1 for e in version_events if e["step"] == "package" and e["status"].startswith("failed"))
    analysis_failures = sum(1 for e in version_events if e["step"] == "analysis" and e["status"] != "ok")

    status = infer_package_status(stats, analysis_count, source_available, full_report, ai_report, event)
    return {
        "package": package,
        "status": status,
        "last_event": event or {},
        "statistics_file": str(stats_path),
        "total_records": stats["total_records"],
        "valid_records": stats["valid_records"],
        "unique_crashes": stats["unique_crashes"],
        "duplicate_crashes": stats["duplicate_crashes"],
        "versions_count": stats["versions_count"],
        "analyzed_versions": analysis_count,
        "source_available": source_available,
        "source_failures": source_failures,
        "package_skips": package_skips,
        "package_failures": package_failures,
        "analysis_failures": analysis_failures,
        "downloaded_deb_files": deb_count,
        "reports": {
            "full_analysis_report_exists": full_report.exists(),
            "ai_analysis_report_exists": ai_report.exists(),
            **paths,
        },
    }


def categorize_root_cause(text):
    lower = text.lower()
    if any(x in lower for x in ("dbus", "qdbus", "pendingcall", "watcher")):
        return "D-Bus连接/回调生命周期"
    if any(x in lower for x in ("xcb", "x11", "display", "qxcb")):
        return "X11/XCB连接"
    if any(x in lower for x in ("qobject", "qwidget", "postevent", "event", "delete", "destroy", "d1ev", "d0ev")):
        return "Qt对象生命周期/事件循环"
    if any(x in lower for x in ("thread", "qtconcurrent", "runfunctiontask", "pthread")):
        return "线程/并发访问"
    if any(x in lower for x in ("assert", "abort", "raise", "sigabrt")):
        return "断言/主动终止"
    if any(x in lower for x in ("null", "segv", "sigsegv", "invalid", "pointer")):
        return "内存访问/空指针"
    return "待人工判断"


def crash_key(crash):
    symbol = crash.get("app_layer_symbol") or ""
    key_frame = crash.get("key_frame") or {}
    if not symbol:
        symbol = key_frame.get("symbol") or ""
    if not symbol:
        frames = crash.get("frames") or []
        if frames:
            symbol = frames[0].get("symbol", "")
    if not symbol:
        symbol = "unknown"
    symbol = re.sub(r"\s+", " ", symbol).strip()
    signal = crash.get("signal") or "UNKNOWN"
    library = crash.get("app_layer_library") or key_frame.get("library") or ""
    return f"{signal}|{library}|{symbol}"


def collect_clusters(workspace, packages):
    clusters = {}
    for package in packages:
        for analysis_file in sorted((workspace / "5.崩溃分析" / package).glob("version_*/analysis.json")):
            data = read_json(analysis_file) or {}
            version = data.get("version") or analysis_file.parent.name.replace("version_", "").replace("_", ".")
            for crash in data.get("crashes", []):
                key = crash_key(crash)
                count = int(crash.get("count", 1) or 1)
                text = " ".join([
                    key,
                    crash.get("description", ""),
                    crash.get("fix_reason", ""),
                    crash.get("stack_info", "")[:500],
                ])
                item = clusters.setdefault(key, {
                    "cluster_id": f"C{len(clusters) + 1:04d}",
                    "key": key,
                    "root_cause_category": categorize_root_cause(text),
                    "total_count": 0,
                    "unique_crashes": 0,
                    "packages": set(),
                    "versions": set(),
                    "signals": set(),
                    "example": crash,
                })
                item["total_count"] += count
                item["unique_crashes"] += 1
                item["packages"].add(package)
                item["versions"].add(f"{package}:{version}")
                item["signals"].add(crash.get("signal") or "UNKNOWN")

    result = []
    for item in clusters.values():
        item["packages"] = sorted(item["packages"])
        item["versions"] = sorted(item["versions"])
        item["signals"] = sorted(item["signals"])
        result.append(item)
    result.sort(key=lambda x: (-x["total_count"], -x["unique_crashes"], x["key"]))
    return result



def normalize_auto_fix_version(version_dir_name, data):
    version = data.get("version") if isinstance(data, dict) else None
    if version:
        return str(version)
    return version_dir_name.replace("version_", "").replace("_", ".")


def classify_auto_fix_result(data):
    if not isinstance(data, dict):
        return "no_fix_output"
    status = data.get("status")
    reason = data.get("reason") or ""
    auto_fixed = data.get("auto_fixed") or []
    analysis_only = data.get("analysis_only") or []
    manual_required = data.get("manual_required") or []
    analysis_report = data.get("analysis_report") or {}
    submitted = bool(data.get("submitted"))
    analysis_report_reason = analysis_report.get("reason") or ""

    if status == "skipped" and "source repository is not available" in reason:
        return "source_repo_missing"
    if "target branch unavailable" in reason or "target branch unavailable" in analysis_report_reason:
        return "target_branch_unavailable"
    if auto_fixed and submitted:
        return "code_fix_submitted"
    if auto_fixed:
        return "code_fix_generated"
    if analysis_report.get("submitted"):
        return "legacy_analysis_report_submitted"
    if analysis_only:
        return "analysis_report_only"
    if manual_required:
        return "manual_required"
    return "no_fix_output"


def summarize_auto_fix_entry(package, version_dir_name, data, result_type, result_path):
    auto_fixed = data.get("auto_fixed") or [] if isinstance(data, dict) else []
    analysis_only = data.get("analysis_only") or [] if isinstance(data, dict) else []
    manual_required = data.get("manual_required") or [] if isinstance(data, dict) else []
    already_fixed = data.get("already_fixed") or [] if isinstance(data, dict) else []
    analysis_report = data.get("analysis_report") or {} if isinstance(data, dict) else {}
    target_missing = 0
    for item in analysis_only + manual_required:
        item_reason = (item.get("reason") or "") if isinstance(item, dict) else ""
        if any(token in item_reason for token in ("target file", "target_file", "not found", "不存在", "missing")):
            target_missing += 1
    return {
        "package": package,
        "version": normalize_auto_fix_version(version_dir_name, data),
        "result_type": result_type,
        "category": classify_auto_fix_result(data),
        "submitted": bool(data.get("submitted")) if isinstance(data, dict) else False,
        "total_fixable_crashes": int(data.get("total_fixable_crashes", 0) or 0) if isinstance(data, dict) else 0,
        "total_crashes": int(data.get("total_crashes", 0) or 0) if isinstance(data, dict) else 0,
        "total_clusters": int(data.get("total_clusters", 0) or 0) if isinstance(data, dict) else 0,
        "auto_fixed_count": len(auto_fixed),
        "analysis_only_count": len(analysis_only),
        "manual_required_count": len(manual_required),
        "already_fixed_count": len(already_fixed),
        "analysis_report_submitted": bool(analysis_report.get("submitted")),
        "analysis_report_commit_hash": analysis_report.get("commit_hash"),
        "commit_hash": data.get("commit_hash") if isinstance(data, dict) else None,
        "commit_hashes": data.get("commit_hashes") or [] if isinstance(data, dict) else [],
        "branch_name": data.get("branch_name") if isinstance(data, dict) else None,
        "reason": data.get("reason") if isinstance(data, dict) else None,
        "target_missing_indicators": target_missing,
        "result_file": str(result_path),
    }


def collect_auto_fix_overview(workspace, packages):
    entries = []
    category_counts = defaultdict(int)
    package_rollup = defaultdict(lambda: {
        "versions": 0,
        "fixable_versions": 0,
        "code_fix_submitted": 0,
        "code_fix_generated": 0,
        "legacy_analysis_report_submitted": 0,
        "analysis_report_only": 0,
        "manual_required": 0,
        "source_repo_missing": 0,
        "target_branch_unavailable": 0,
        "no_fix_output": 0,
        "target_missing_indicators": 0,
    })

    for package in packages:
        package_dir = workspace / "5.崩溃分析" / package
        for version_dir in sorted(package_dir.glob("version_*")):
            candidates = [
                ("cluster", version_dir / "auto_fix_clusters_result.json"),
                ("spec", version_dir / "auto_fix_result.json"),
            ]
            for result_type, result_path in candidates:
                if not result_path.exists():
                    continue
                data = read_json(result_path) or {}
                entry = summarize_auto_fix_entry(package, version_dir.name, data, result_type, result_path)
                entries.append(entry)
                category_counts[entry["category"]] += 1
                rollup = package_rollup[package]
                rollup["versions"] += 1
                if any([
                    entry["total_fixable_crashes"] > 0,
                    entry["total_clusters"] > 0,
                    entry["analysis_only_count"] > 0,
                    entry["manual_required_count"] > 0,
                    entry["auto_fixed_count"] > 0,
                ]):
                    rollup["fixable_versions"] += 1
                rollup[entry["category"]] += 1
                rollup["target_missing_indicators"] += entry["target_missing_indicators"]
                break

    entries.sort(key=lambda item: (item["package"], item["version"], item["result_type"]))
    package_summary = [{"package": package, **metrics} for package, metrics in sorted(package_rollup.items())]
    return {
        "generated_at": datetime.now().isoformat(),
        "workspace": str(workspace),
        "total_versions_with_auto_fix_results": len(entries),
        "versions_with_fixable_output": sum(
            1 for e in entries
            if any([
                e["total_fixable_crashes"] > 0,
                e["total_clusters"] > 0,
                e["analysis_only_count"] > 0,
                e["manual_required_count"] > 0,
                e["auto_fixed_count"] > 0,
            ])
        ),
        "category_counts": dict(sorted(category_counts.items())),
        "packages": package_summary,
        "entries": entries,
    }


def collect_new_crash_overview(workspace, packages):
    entries = []
    package_counts = {}
    total_new = 0
    packages_with_new = 0
    baseline_root = ''
    for package in packages:
        diff_path = workspace / '2.数据筛选' / f'{package}_crash_baseline_diff.json'
        data = read_json(diff_path)
        if not data:
            continue
        new_count = int(data.get('new_unique_count', 0) or 0)
        current_count = int(data.get('current_unique_count', 0) or 0)
        baseline_before = int(data.get('baseline_unique_count_before', 0) or 0)
        baseline_after = int(data.get('baseline_unique_count_after', 0) or 0)
        baseline_root = baseline_root or data.get('baseline_root', '')
        package_counts[package] = new_count
        total_new += new_count
        if new_count > 0:
            packages_with_new += 1
        for row in data.get('new_crashes', []):
            entries.append({
                'package': package,
                'version': row.get('Version', ''),
                'signal': row.get('Sig', ''),
                'exe': row.get('Exe', ''),
                'count': row.get('Count', ''),
                'unique_key': row.get('UniqueKey', ''),
            })
    entries.sort(key=lambda item: (item['package'], item['version'], item['signal'], item['exe'], item['unique_key']))
    return {
        'generated_at': datetime.now().isoformat(timespec='seconds'),
        'workspace': str(workspace),
        'baseline_root': baseline_root,
        'packages_scanned': len(packages),
        'packages_with_new_crashes': packages_with_new,
        'total_new_unique_crashes': total_new,
        'package_new_counts': dict(sorted(package_counts.items())),
        'entries': entries,
    }


def render_new_crash_overview_md(overview):
    lines = [
        '# New Crash Overview',
        '',
        f"生成时间: {overview.get('generated_at', '')}",
        f"Workspace: {overview.get('workspace', '')}",
        f"Baseline Root: {overview.get('baseline_root', '')}",
        '',
        '## 总览',
        '',
        f"- 扫描包数: {overview.get('packages_scanned', 0)}",
        f"- 有新增崩溃的包数: {overview.get('packages_with_new_crashes', 0)}",
        f"- 新增唯一崩溃总数: {overview.get('total_new_unique_crashes', 0)}",
        '',
        '## 按包统计',
        '',
    ]
    package_counts = overview.get('package_new_counts', {})
    if package_counts:
        lines.append('| package | new_unique_crashes |')
        lines.append('|---------|--------------------|')
        for package, count in sorted(package_counts.items()):
            lines.append(f'| {package} | {count} |')
    else:
        lines.append('无')
    lines.extend(['', '## 新增崩溃明细', ''])
    entries = overview.get('entries', [])
    if entries:
        lines.append('| package | version | signal | exe | count | unique_key |')
        lines.append('|---------|---------|--------|-----|-------|------------|')
        for item in entries:
            lines.append(f"| {item['package']} | {item['version']} | {item['signal']} | {item['exe']} | {item['count']} | {item['unique_key']} |")
    else:
        lines.append('无新增唯一崩溃')
    lines.append('')
    return "\n".join(lines)


def render_auto_fix_overview_md(overview):
    lines = [
        "# Auto Fix Overview",
        "",
        f"生成时间: {overview.get('generated_at', '')}",
        f"Workspace: {overview.get('workspace', '')}",
        "",
        "## 总览",
        "",
        f"- 产出 auto-fix 结果的版本数: {overview.get('total_versions_with_auto_fix_results', 0)}",
        f"- 含 fixable / analysis-only / manual-required 输出的版本数: {overview.get('versions_with_fixable_output', 0)}",
        "",
        "## 分类统计",
        "",
    ]
    category_counts = overview.get("category_counts", {})
    if category_counts:
        for key, value in sorted(category_counts.items()):
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- 无 auto-fix 结果")

    lines.extend(["", "## 按包汇总", ""])
    packages = overview.get("packages", [])
    if packages:
        lines.append("| package | versions | fixable_versions | code_fix_submitted | code_fix_generated | legacy_analysis_report_submitted | analysis_report_only | manual_required | source_repo_missing | target_branch_unavailable | target_missing_indicators |")
        lines.append("|---------|----------|------------------|--------------------|--------------------|----------------------------------|----------------------|----------------|---------------------|---------------------------|---------------------------|")
        for item in packages:
            lines.append(
                f"| {item['package']} | {item['versions']} | {item['fixable_versions']} | {item['code_fix_submitted']} | {item['code_fix_generated']} | {item['legacy_analysis_report_submitted']} | {item['analysis_report_only']} | {item['manual_required']} | {item['source_repo_missing']} | {item['target_branch_unavailable']} | {item['target_missing_indicators']} |"
            )
    else:
        lines.append("无")

    lines.extend(["", "## 版本明细", ""])
    entries = overview.get("entries", [])
    if entries:
        lines.append("| package | version | type | category | submitted | auto_fixed | analysis_only | manual_required | legacy_analysis_report_submitted | result_file |")
        lines.append("|---------|---------|------|----------|-----------|------------|---------------|-----------------|----------------------------------|-------------|")
        for item in entries:
            lines.append(
                f"| {item['package']} | {item['version']} | {item['result_type']} | {item['category']} | {str(item['submitted'])} | {item['auto_fixed_count']} | {item['analysis_only_count']} | {item['manual_required_count']} | {str(item['analysis_report_submitted'])} | {item['result_file']} |"
            )
    else:
        lines.append("无")
    lines.append("")
    return "\n".join(lines)


def markdown_table(headers, rows):
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return "\n".join(lines)


def render_final_analysis_summary_md(manifest, auto_fix_overview, new_crash_overview):
    """Render the compact human-facing final report for a completed workspace."""
    packages = manifest.get("packages", [])
    totals = manifest.get("totals", {})
    category_counts = auto_fix_overview.get("category_counts", {})
    auto_entries = auto_fix_overview.get("entries", [])

    status_counts = defaultdict(int)
    for entry in packages:
        status_counts[entry.get("status", "unknown")] += 1

    by_unique = sorted(
        [entry for entry in packages if int(entry.get("unique_crashes", 0) or 0) > 0],
        key=lambda entry: (-int(entry.get("unique_crashes", 0) or 0), -int(entry.get("valid_records", 0) or 0), entry.get("package", "")),
    )
    by_records = sorted(
        [entry for entry in packages if int(entry.get("valid_records", 0) or 0) > 0],
        key=lambda entry: (-int(entry.get("valid_records", 0) or 0), -int(entry.get("unique_crashes", 0) or 0), entry.get("package", "")),
    )
    partial_packages = [
        entry for entry in packages
        if entry.get("status") == "partial"
        or int(entry.get("analyzed_versions", 0) or 0) < int(entry.get("versions_count", 0) or 0)
    ]
    source_problem_packages = [
        entry for entry in packages
        if int(entry.get("source_failures", 0) or 0) > 0 or entry.get("status") == "completed_data_only"
    ]

    code_submitted = [
        entry for entry in auto_entries
        if entry.get("category") == "code_fix_submitted" or entry.get("submitted") is True
    ]
    manual_required = [
        entry for entry in auto_entries
        if entry.get("category") == "manual_required" or int(entry.get("manual_required_count", 0) or 0) > 0
    ]
    analysis_report_only = [entry for entry in auto_entries if entry.get("category") == "analysis_report_only"]
    source_repo_missing = [entry for entry in auto_entries if entry.get("category") == "source_repo_missing"]

    def count_by_package(entries):
        counts = defaultdict(int)
        for item in entries:
            counts[item.get("package", "unknown")] += 1
        return sorted(counts.items(), key=lambda item: (-item[1], item[0]))

    total_packages = totals.get("packages", len(packages))
    package_status_line = f"{total_packages}/{total_packages} completed or finalized"
    if any(entry.get("status") in {"running", "pending"} for entry in packages):
        package_status_line = f"{sum(1 for entry in packages if entry.get('status') not in {'running', 'pending'})}/{total_packages} finalized"

    lines = [
        "# Coredump 自动化分析汇总报告",
        "",
        f"生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Workspace: `{manifest.get('workspace', '')}`",
        f"数据范围: {manifest.get('date_range', '') or '未知'}",
        f"汇总刷新时间: {manifest.get('generated_at', '')}",
        "",
        "## 结论",
        "",
        f"- 本轮包级分析状态：{package_status_line}。",
        f"- 汇总层面：完成 {totals.get('completed', 0)} 个包，部分完成 {totals.get('partial', 0)} 个包，失败 {totals.get('failed', 0)} 个包。",
        f"- 共处理有效记录 {totals.get('valid_records', 0)} 条，归并出唯一崩溃 {totals.get('unique_crashes', 0)} 个，涉及版本 {totals.get('versions', 0)} 个，已分析版本 {totals.get('analyzed_versions', 0)} 个。",
        f"- 新增唯一崩溃：{new_crash_overview.get('total_new_unique_crashes', totals.get('new_unique_crashes', 0))} 个；有新增崩溃的包：{new_crash_overview.get('packages_with_new_crashes', totals.get('packages_with_new_crashes', 0))} 个。",
        f"- Auto-fix：产出结果版本 {auto_fix_overview.get('total_versions_with_auto_fix_results', 0)} 个，其中 fixable/analysis-only/manual-required 输出版本 {auto_fix_overview.get('versions_with_fixable_output', 0)} 个；真实代码修复提交 {category_counts.get('code_fix_submitted', 0)} 个。",
        "",
        "## 总体指标",
        "",
        markdown_table(["指标", "数值"], [
            ["包数量", totals.get("packages", 0)],
            ["包级状态", package_status_line],
            ["汇总完成包", totals.get("completed", 0)],
            ["部分完成包", totals.get("partial", 0)],
            ["失败包", totals.get("failed", 0)],
            ["有效记录", totals.get("valid_records", 0)],
            ["唯一崩溃", totals.get("unique_crashes", 0)],
            ["版本数", totals.get("versions", 0)],
            ["已分析版本", totals.get("analyzed_versions", 0)],
            ["新增唯一崩溃", totals.get("new_unique_crashes", 0)],
        ]),
        "",
        "## 包状态分布",
        "",
        markdown_table(["状态", "包数"], sorted(status_counts.items())) if status_counts else "无",
        "",
        "## 唯一崩溃 Top 包",
        "",
        markdown_table(
            ["包", "有效记录", "唯一崩溃", "版本", "已分析版本", "状态"],
            [[entry.get("package", ""), entry.get("valid_records", 0), entry.get("unique_crashes", 0), entry.get("versions_count", 0), entry.get("analyzed_versions", 0), entry.get("status", "")] for entry in by_unique[:15]],
        ) if by_unique else "无",
        "",
        "## 有效记录 Top 包",
        "",
        markdown_table(
            ["包", "有效记录", "唯一崩溃", "版本", "已分析版本", "状态"],
            [[entry.get("package", ""), entry.get("valid_records", 0), entry.get("unique_crashes", 0), entry.get("versions_count", 0), entry.get("analyzed_versions", 0), entry.get("status", "")] for entry in by_records[:15]],
        ) if by_records else "无",
        "",
        "## 部分完成 / 覆盖缺口",
        "",
    ]

    if partial_packages:
        lines.append(markdown_table(
            ["包", "状态", "版本", "已分析版本", "有效记录", "唯一崩溃"],
            [[entry.get("package", ""), entry.get("status", ""), entry.get("versions_count", 0), entry.get("analyzed_versions", 0), entry.get("valid_records", 0), entry.get("unique_crashes", 0)] for entry in partial_packages],
        ))
        lines.extend(["", "说明：`package_status.tsv` 记录包级执行状态；`run_manifest` 会进一步按版本覆盖率统计 partial。"])
    else:
        lines.append("无。")

    lines.extend([
        "",
        "## Auto-fix 分类",
        "",
        markdown_table(["分类", "版本数"], sorted(category_counts.items())) if category_counts else "无 auto-fix 结果。",
        "",
        "### 已提交真实代码修复",
        "",
    ])
    if code_submitted:
        lines.append(markdown_table(
            ["包", "版本", "分支", "提交", "结果文件"],
            [[
                entry.get("package", ""),
                entry.get("version", ""),
                entry.get("branch_name", ""),
                ", ".join(entry.get("commit_hashes") or ([entry.get("commit_hash")] if entry.get("commit_hash") else [])),
                entry.get("result_file", ""),
            ] for entry in code_submitted],
        ))
    else:
        lines.append("无。")

    lines.extend(["", "### 需要人工处理的包", ""])
    manual_counts = count_by_package(manual_required)
    lines.append(markdown_table(["包", "manual_required 版本数"], manual_counts) if manual_counts else "无。")

    lines.extend(["", "### Analysis report only 的包", ""])
    analysis_counts = count_by_package(analysis_report_only)
    lines.append(markdown_table(["包", "analysis_report_only 版本数"], analysis_counts) if analysis_counts else "无。")

    lines.extend(["", "### 源码缺失", ""])
    source_missing_counts = count_by_package(source_repo_missing)
    lines.append(markdown_table(["包", "source_repo_missing 版本数"], source_missing_counts) if source_missing_counts else "无。")

    lines.extend(["", "## 源码/数据问题包", ""])
    if source_problem_packages:
        lines.append(markdown_table(
            ["包", "状态", "源码失败", "有效记录", "唯一崩溃"],
            [[entry.get("package", ""), entry.get("status", ""), entry.get("source_failures", 0), entry.get("valid_records", 0), entry.get("unique_crashes", 0)] for entry in source_problem_packages],
        ))
    else:
        lines.append("无。")

    lines.extend([
        "",
        "## 建议后续动作",
        "",
        "1. 优先核查已提交的真实代码修复，确认 Gerrit review 与源码改动是否符合预期。",
        "2. 对 manual_required 集中的包做专项人工分析；如存在 partial 包，同时补齐版本覆盖缺口。",
        "3. 对 source_repo_missing / completed_data_only 的包补齐源码映射或分支信息后重跑对应包/版本。",
        "4. analysis_report_only 不计为真实修复，除非明确需要保留分析记录，否则不要当作代码修复提交统计。",
        "",
        "## 相关原始文件",
        "",
    ])
    summary_dir = Path(manifest.get("summary_dir") or (Path(manifest.get("workspace", ".")) / SUMMARY_DIR_NAME))
    for name in [
        "run_manifest.md",
        "run_manifest.json",
        "auto_fix_overview.md",
        "auto_fix_overview.json",
        "new_crashes_overview.md",
        "new_crashes_overview.json",
        "package_status.tsv",
        "version_status.tsv",
    ]:
        path = summary_dir / name
        if path.exists():
            lines.append(f"- `{path}`")

    lines.append("")
    return "\n".join(lines)

def clean_version_label(value):
    value = (value or "").strip()
    if not value:
        return ""
    if ":" in value:
        value = value.split(":", 1)[1]
    value = re.sub(r"-1$", "", value)
    return value


def load_expected_versions(workspace, package):
    path = workspace / "2.数据筛选" / f"{package}_crash_versions.txt"
    versions = []
    if not path.exists():
        return versions
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            rest = line.rsplit(":", 1)[0]
            versions.append(clean_version_label(rest))
    return versions


def load_auto_fix_category_for_version(workspace, package, version):
    version_dir = clean_version_label(version).replace('.', '_').replace('+', '_').replace('-', '_')
    base = workspace / "5.崩溃分析" / package / f"version_{version_dir}"
    for result_file in (base / "auto_fix_clusters_result.json", base / "auto_fix_result.json"):
        if result_file.exists():
            data = read_json(result_file) or {}
            return classify_auto_fix_result(data), data
    return None, None


def build_retry_targets(workspace, manifest, version_statuses, run_context):
    retry_package_statuses = {"failed", "partial", "running", "pending"}
    retry_packages = []
    retry_versions = []

    for entry in manifest["packages"]:
        package = entry["package"]
        if entry["status"] in retry_package_statuses:
            retry_packages.append(package)

        events = version_statuses.get(package, [])
        by_version = defaultdict(list)
        for event in events:
            version = clean_version_label(event.get("version", ""))
            if version:
                by_version[version].append(event)

        expected_versions = load_expected_versions(workspace, package)
        for version in expected_versions:
            version_events = by_version.get(version, [])
            step_status = {e["step"]: e["status"] for e in version_events}
            failed_steps = [e["step"] for e in version_events if e["status"] not in ("ok", "skipped_no_sudo")]
            last_message = version_events[-1]["message"] if version_events else "no execution record"
            needs_retry = False
            auto_fix_category, auto_fix_data = load_auto_fix_category_for_version(workspace, package, version)

            if not version_events:
                needs_retry = True
                failed_steps = ["missing"]
            elif step_status.get("analysis") != "ok":
                needs_retry = True
            elif step_status.get("source", "").startswith("failed"):
                needs_retry = True
            elif any(
                status.startswith("failed")
                for step, status in step_status.items()
                if not (
                    step == "autofix"
                    and auto_fix_category in {"target_branch_unavailable", "legacy_analysis_report_submitted", "analysis_report_only", "manual_required", "source_repo_missing", "no_fix_output"}
                )
            ):
                needs_retry = True

            if needs_retry:
                retry_strategy, step_retry_command = build_step_retry_strategy(
                    package, version, failed_steps, workspace, run_context
                )
                retry_versions.append({
                    "package": package,
                    "version": version,
                    "failed_steps": failed_steps,
                    "last_message": last_message,
                    "command": build_retry_command(package, workspace, run_context, version),
                    "retry_strategy": retry_strategy,
                    "step_command": step_retry_command,
                    "auto_fix_category": auto_fix_category,
                    "auto_fix_reason": (auto_fix_data or {}).get("reason") or ((auto_fix_data or {}).get("analysis_report") or {}).get("reason"),
                })

    retry_packages = sorted(set(retry_packages))
    retry_versions.sort(key=lambda x: (x["package"], x["version"]))
    return retry_packages, retry_versions


def build_retry_command(package, workspace, run_context, version=None):
    parts = [
        "bash coredump-full-analysis/scripts/analyze_crash_complete.sh" if version else "bash run_analysis_agent.sh",
        f"--package {package}" if version else f"--packages {package}",
        f"--workspace {workspace}",
    ]
    arch = run_context.get("arch", "")
    sys_version = run_context.get("sys_version", "")
    start_date = run_context.get("start_date", "")
    end_date = run_context.get("end_date", "")
    if arch:
        parts.append(f"--arch {arch}")
    if sys_version:
        parts.append(f"--sys-version {sys_version}")
    if start_date:
        parts.append(f"--start-date {start_date}")
    if end_date:
        parts.append(f"--end-date {end_date}")
    if version:
        parts.append(f"--versions {version}")
    return " ".join(parts)


def build_retry_step_command(package, version, workspace, run_context, strategy):
    parts = [
        "bash coredump-full-analysis/scripts/validation/run_retry_step.sh",
        f"--package {package}",
        f"--version {version}",
        f"--workspace {workspace}",
        f"--strategy {strategy}",
    ]
    arch = run_context.get("arch", "")
    sys_version = run_context.get("sys_version", "")
    start_date = run_context.get("start_date", "")
    end_date = run_context.get("end_date", "")
    if arch:
        parts.append(f"--arch {arch}")
    if sys_version:
        parts.append(f"--sys-version {sys_version}")
    if start_date:
        parts.append(f"--start-date {start_date}")
    if end_date:
        parts.append(f"--end-date {end_date}")
    return " ".join(parts)


def build_step_retry_strategy(package, version, failed_steps, workspace, run_context):
    normalized_steps = [step for step in failed_steps if step]
    if "missing" in normalized_steps or "source" in normalized_steps:
        return "full_version_rerun", build_retry_step_command(package, version, workspace, run_context, "full_version_rerun")

    if not normalized_steps:
        return "full_version_rerun", build_retry_step_command(package, version, workspace, run_context, "full_version_rerun")

    if normalized_steps == ["analysis"]:
        return "analysis_only", build_retry_step_command(package, version, workspace, run_context, "analysis_only")

    if set(normalized_steps).issubset({"package", "analysis"}):
        return "package_then_analysis", build_retry_step_command(package, version, workspace, run_context, "package_then_analysis")

    return "full_version_rerun", build_retry_step_command(package, version, workspace, run_context, "full_version_rerun")


def generate_manifest(workspace, packages, package_statuses, version_statuses, date_range_label):
    entries = [
        package_entry(workspace, package, package_statuses.get(package), version_statuses.get(package, []))
        for package in packages
    ]
    totals = {
        "packages": len(entries),
        "completed": sum(1 for e in entries if e["status"] in ("completed", "completed_no_data", "completed_data_only", "skipped_completed")),
        "failed": sum(1 for e in entries if e["status"] == "failed"),
        "partial": sum(1 for e in entries if e["status"] == "partial"),
        "pending": sum(1 for e in entries if e["status"] == "pending"),
        "valid_records": sum(e["valid_records"] for e in entries),
        "unique_crashes": sum(e["unique_crashes"] for e in entries),
        "versions": sum(e["versions_count"] for e in entries),
        "analyzed_versions": sum(e["analyzed_versions"] for e in entries),
    }
    return {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "workspace": str(workspace),
        "summary_dir": str(workspace / SUMMARY_DIR_NAME),
        "date_range": date_range_label,
        "totals": totals,
        "packages": entries,
    }


def write_manifest_md(path, manifest):
    lines = [
        "# 运行 Manifest\n\n",
        f"**生成时间**: {manifest['generated_at']}\n\n",
        f"**工作目录**: `{manifest['workspace']}`\n\n",
    ]
    if manifest.get("date_range"):
        lines.append(f"**日期范围**: {manifest['date_range']}\n\n")
    totals = manifest["totals"]
    lines.extend([
        "## 总体状态\n\n",
        f"- 包数量: {totals['packages']}\n",
        f"- 完成: {totals['completed']}\n",
        f"- 失败: {totals['failed']}\n",
        f"- 部分完成: {totals['partial']}\n",
        f"- 待处理: {totals['pending']}\n",
        f"- 有效记录: {totals['valid_records']}\n",
        f"- 唯一崩溃: {totals['unique_crashes']}\n",
        f"- 版本数: {totals['versions']}\n",
        f"- 已分析版本: {totals['analyzed_versions']}\n",
        f"- 新增唯一崩溃: {totals.get('new_unique_crashes', 0)}\n",
        f"- 出现新增崩溃的包: {totals.get('packages_with_new_crashes', 0)}\n\n",
        "## 包状态\n\n",
        "| 包 | 状态 | 有效记录 | 唯一崩溃 | 版本 | 已分析版本 | 源码 | 源码失败 | 包跳过 | 报告 |\n",
        "|----|------|----------|----------|------|------------|------|----------|--------|------|\n",
    ])
    for entry in manifest["packages"]:
        reports_ok = "yes" if entry["reports"]["ai_analysis_report_exists"] else "no"
        source = "yes" if entry["source_available"] else "no"
        lines.append(
            f"| {entry['package']} | {entry['status']} | {entry['valid_records']} | "
            f"{entry['unique_crashes']} | {entry['versions_count']} | {entry['analyzed_versions']} | "
            f"{source} | {entry['source_failures']} | {entry['package_skips']} | {reports_ok} |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_all_summary(path, manifest):
    lines = [
        "# 全包崩溃分析汇总\n\n",
        f"**生成时间**: {manifest['generated_at']}\n\n",
        f"**工作目录**: `{manifest['workspace']}`\n\n",
    ]
    if manifest.get("date_range"):
        lines.append(f"**日期范围**: {manifest['date_range']}\n\n")
    totals = manifest["totals"]
    lines.extend([
        "## 总览\n\n",
        f"- 包数量: {totals['packages']}\n",
        f"- 有效崩溃记录: {totals['valid_records']}\n",
        f"- 唯一崩溃: {totals['unique_crashes']}\n",
        f"- 版本数: {totals['versions']}\n",
        f"- 已分析版本: {totals['analyzed_versions']}\n",
        f"- 新增唯一崩溃: {totals.get('new_unique_crashes', 0)}\n",
        f"- 出现新增崩溃的包: {totals.get('packages_with_new_crashes', 0)}\n\n",
        "## Top 包\n\n",
        "| 包 | 状态 | 有效记录 | 唯一崩溃 | 版本数 | 报告 |\n",
        "|----|------|----------|----------|--------|------|\n",
    ])
    ranked = sorted(manifest["packages"], key=lambda e: (-e["unique_crashes"], -e["valid_records"], e["package"]))
    for entry in ranked:
        report = entry["reports"]["ai_analysis_report"]
        lines.append(
            f"| {entry['package']} | {entry['status']} | {entry['valid_records']} | "
            f"{entry['unique_crashes']} | {entry['versions_count']} | `{report}` |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_cluster_md(path, clusters):
    lines = [
        "# 跨包问题簇汇总\n\n",
        f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n",
        f"**问题簇数量**: {len(clusters)}\n\n",
        "| ID | 类别 | 总次数 | 唯一崩溃 | 包 | 信号 | 关键符号 |\n",
        "|----|------|--------|----------|----|------|----------|\n",
    ]
    for cluster in clusters[:80]:
        key_symbol = cluster["key"].split("|")[-1]
        lines.append(
            f"| {cluster['cluster_id']} | {cluster['root_cause_category']} | {cluster['total_count']} | "
            f"{cluster['unique_crashes']} | {', '.join(cluster['packages'][:5])} | "
            f"{', '.join(cluster['signals'])} | `{key_symbol}` |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_packages(path, retry_packages):
    lines = ["# 需要重跑的包\n"]
    for package in retry_packages:
        lines.append(f"{package}\n")
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_versions_tsv(path, retry_versions):
    lines = ["package\tversion\tfailed_steps\tretry_strategy\tlast_message\tcommand\tstep_command\n"]
    for item in retry_versions:
        lines.append(
            f"{item['package']}\t{item['version']}\t{','.join(item['failed_steps'])}\t"
            f"{item['retry_strategy']}\t{item['last_message']}\t{item['command']}\t{item['step_command']}\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_versions_md(path, retry_versions):
    lines = [
        "# 需要重跑的版本\n\n",
        f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n",
        "| 包 | 版本 | 失败步骤 | 重跑策略 | 说明 | 重跑命令 |\n",
        "|----|------|----------|----------|------|----------|\n",
    ]
    for item in retry_versions:
        lines.append(
            f"| {item['package']} | {item['version']} | {', '.join(item['failed_steps'])} | {item['retry_strategy']} | "
            f"{item['last_message']} | `{item['command']}` |\n"
        )
    path.write_text("".join(lines), encoding="utf-8")


def write_retry_commands(path, workspace, retry_packages, run_context):
    summary_dir_literal = json.dumps(str(workspace / SUMMARY_DIR_NAME), ensure_ascii=False)
    lines = [
        "#!/bin/bash\n",
        "set -e\n\n",
        f"WORKSPACE={json.dumps(str(workspace))}\n\n",
        f"SUMMARY_DIR={summary_dir_literal}\n\n",
    ]
    for package in retry_packages:
        command = build_retry_command(package, "$WORKSPACE", run_context)
        lines.append(f"{command}\n")
    lines.extend(build_summary_refresh_block(run_context))
    if retry_packages:
        lines.extend([
            "\n# 校验包级重跑结果\n",
            "python3 coredump-full-analysis/scripts/validation/verify_retry_targets.py \\\n",
            "  --summary-dir \"$SUMMARY_DIR\" \\\n",
            f"  --packages {json.dumps(','.join(retry_packages), ensure_ascii=False)}\n",
        ])
    path.write_text("".join(lines), encoding="utf-8")
    path.chmod(0o755)


def write_retry_version_commands(path, workspace, retry_versions, run_context):
    summary_dir_literal = json.dumps(str(workspace / SUMMARY_DIR_NAME), ensure_ascii=False)
    lines = [
        "#!/bin/bash\n",
        "set -e\n\n",
        f"WORKSPACE={json.dumps(str(workspace))}\n\n",
        f"SUMMARY_DIR={summary_dir_literal}\n",
        "TARGET_VERSIONS_FILE=\"$SUMMARY_DIR/.retry_versions_targets.tsv\"\n\n",
    ]
    if retry_versions:
        lines.append("cat > \"$TARGET_VERSIONS_FILE\" <<'EOF'\n")
        for item in retry_versions:
            lines.append(f"{item['package']}\t{item['version']}\n")
        lines.append("EOF\n\n")
    for item in retry_versions:
        command = build_retry_command(item["package"], "$WORKSPACE", run_context, item["version"])
        lines.append(f"{command}\n")
    lines.extend(build_summary_refresh_block(run_context))
    lines.extend([
        "\n# 校验版本级重跑结果\n",
        "# marker: verify_retry_targets.py\n",
    ])
    if retry_versions:
        lines.extend([
            "python3 coredump-full-analysis/scripts/validation/verify_retry_targets.py \\\n",
            "  --summary-dir \"$SUMMARY_DIR\" \\\n",
            "  --versions-file \"$TARGET_VERSIONS_FILE\"\n",
        ])
    path.write_text("".join(lines), encoding="utf-8")
    path.chmod(0o755)


def write_retry_failed_step_commands(path, workspace, retry_versions, run_context):
    summary_dir_literal = json.dumps(str(workspace / SUMMARY_DIR_NAME), ensure_ascii=False)
    lines = [
        "#!/bin/bash\n",
        "set -e\n\n",
        f"WORKSPACE={json.dumps(str(workspace))}\n\n",
        f"SUMMARY_DIR={summary_dir_literal}\n",
        "TARGET_VERSIONS_FILE=\"$SUMMARY_DIR/.retry_failed_step_targets.tsv\"\n\n",
    ]
    if retry_versions:
        lines.append("cat > \"$TARGET_VERSIONS_FILE\" <<'EOF'\n")
        for item in retry_versions:
            lines.append(f"{item['package']}\t{item['version']}\n")
        lines.append("EOF\n\n")
    for item in retry_versions:
        command = item.get("step_command", "")
        if not command:
            continue
        command = command.replace(str(workspace), "$WORKSPACE")
        lines.append(f"# {item['package']} {item['version']} [{item['retry_strategy']}]\n")
        lines.append(f"{command}\n\n")
    lines.extend(build_summary_refresh_block(run_context))
    lines.extend([
        "\n# 失败步骤重跑脚本入口\n",
        "# marker: run_retry_step.sh\n",
        "# 校验失败步骤重跑结果\n",
    ])
    if retry_versions:
        lines.extend([
            "python3 coredump-full-analysis/scripts/validation/verify_retry_targets.py \\\n",
            "  --summary-dir \"$SUMMARY_DIR\" \\\n",
            "  --versions-file \"$TARGET_VERSIONS_FILE\"\n",
        ])
    path.write_text("".join(lines), encoding="utf-8")
    path.chmod(0o755)


def build_summary_refresh_block(run_context):
    packages = run_context.get("packages", "")
    date_range_label = run_context.get("date_range_label", "")
    packages_arg = json.dumps(packages, ensure_ascii=False)
    date_range_arg = json.dumps(date_range_label, ensure_ascii=False)
    return [
        "\n# 刷新 workspace 汇总\n",
        "python3 coredump-full-analysis/scripts/reporting/generate_workspace_summary.py \\\n",
        "  --workspace \"$WORKSPACE\" \\\n",
        f"  --packages {packages_arg} \\\n",
        f"  --date-range-label {date_range_arg}\n",
    ]


def write_retry_summary_md(path, manifest, retry_packages, retry_versions):
    package_map = {entry["package"]: entry for entry in manifest["packages"]}
    retry_by_package = defaultdict(list)
    for item in retry_versions:
        retry_by_package[item["package"]].append(item)

    lines = [
        "# 重跑摘要\n\n",
        f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n",
        f"- 需要重跑的包: {len(retry_packages)}\n",
        f"- 需要重跑的版本: {len(retry_versions)}\n\n",
    ]

    if retry_packages:
        lines.extend([
            "## 包级重跑\n\n",
            "| 包 | 当前状态 | 最近结果 | 有效记录 | 唯一崩溃 | 说明 |\n",
            "|----|----------|----------|----------|----------|------|\n",
        ])
        for package in retry_packages:
            entry = package_map.get(package, {})
            last_event = entry.get("last_event", {}) if entry else {}
            message = last_event.get("message", "") or "reported by manifest"
            lines.append(
                f"| {package} | {entry.get('status', 'unknown')} | {last_event.get('status', 'unknown')} | "
                f"{entry.get('valid_records', 0)} | {entry.get('unique_crashes', 0)} | {message} |\n"
            )
        lines.append("\n")

    if retry_versions:
        lines.extend([
            "## 版本级重跑\n\n",
            "| 包 | 版本 | 失败步骤 | 最后信息 |\n",
            "|----|------|----------|----------|\n",
        ])
        for item in retry_versions:
            lines.append(
                f"| {item['package']} | {item['version']} | {', '.join(item['failed_steps'])} | "
                f"{item['last_message']} |\n"
            )
        lines.append("\n")

        lines.append("## 按包汇总\n\n")
        for package in sorted(retry_by_package):
            lines.append(f"### {package}\n\n")
            for item in retry_by_package[package]:
                lines.append(
                    f"- 版本 `{item['version']}`: 步骤 `{', '.join(item['failed_steps'])}`; "
                    f"策略 `{item['retry_strategy']}`; {item['last_message']}\n"
                )
            lines.append("\n")
    else:
        lines.append("## 版本级重跑\n\n当前没有需要精确重跑的版本。\n")

    lines.extend([
        "## 相关文件\n\n",
        f"- `retry_packages.txt`\n",
        f"- `retry_versions.tsv`\n",
        f"- `retry_commands.sh`\n",
        f"- `retry_versions.sh`\n",
        f"- `retry_failed_steps.sh`\n",
        f"- `validate_workspace_retry_closure.py`\n",
        f"- `validate_workspace.sh`\n",
    ])
    path.write_text("".join(lines), encoding="utf-8")


def main():
    args = parse_args()
    workspace = Path(args.workspace)
    summary_dir = workspace / SUMMARY_DIR_NAME
    summary_dir.mkdir(parents=True, exist_ok=True)
    run_context = load_run_context(summary_dir)

    requested = split_packages(args.packages)
    packages = discover_packages(workspace, requested)
    package_statuses = latest_status_by_package(args.status_file or str(summary_dir / "package_status.tsv"))
    version_statuses = load_version_status(args.version_status_file or str(summary_dir / "version_status.tsv"))

    for pkg in split_packages(args.failed_packages):
        package_statuses[pkg] = {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "status": "failed",
            "exit_code": "1",
            "message": "reported by caller",
        }

    manifest = generate_manifest(workspace, packages, package_statuses, version_statuses, args.date_range_label)
    clusters = collect_clusters(workspace, packages)
    new_crash_overview = collect_new_crash_overview(workspace, packages)
    manifest['totals']['new_unique_crashes'] = new_crash_overview.get('total_new_unique_crashes', 0)
    manifest['totals']['packages_with_new_crashes'] = new_crash_overview.get('packages_with_new_crashes', 0)
    retry_packages, retry_versions = build_retry_targets(workspace, manifest, version_statuses, run_context)

    if args.list_failed:
        retry_statuses = {"failed", "partial", "running", "pending"}
        for entry in manifest["packages"]:
            if entry["status"] in retry_statuses:
                print(entry["package"])
        return

    write_json(summary_dir / "run_manifest.json", manifest)
    write_manifest_md(summary_dir / "run_manifest.md", manifest)
    write_json(summary_dir / "all_packages_summary.json", {
        "generated_at": manifest["generated_at"],
        "workspace": manifest["workspace"],
        "date_range": manifest["date_range"],
        "totals": manifest["totals"],
        "packages": manifest["packages"],
        "new_crash_overview": new_crash_overview,
    })
    write_all_summary(summary_dir / "all_packages_summary.md", manifest)
    write_json(summary_dir / "new_crashes_overview.json", new_crash_overview)
    (summary_dir / "new_crashes_overview.md").write_text(render_new_crash_overview_md(new_crash_overview), encoding="utf-8")
    write_json(summary_dir / "root_cause_clusters.json", clusters)
    write_cluster_md(summary_dir / "root_cause_clusters.md", clusters)
    auto_fix_overview = collect_auto_fix_overview(workspace, packages)
    write_json(summary_dir / "auto_fix_overview.json", auto_fix_overview)
    (summary_dir / "auto_fix_overview.md").write_text(render_auto_fix_overview_md(auto_fix_overview), encoding="utf-8")
    (summary_dir / "analysis_summary_final.md").write_text(
        render_final_analysis_summary_md(manifest, auto_fix_overview, new_crash_overview),
        encoding="utf-8",
    )
    write_retry_packages(summary_dir / "retry_packages.txt", retry_packages)
    write_json(summary_dir / "retry_versions.json", retry_versions)
    write_retry_versions_tsv(summary_dir / "retry_versions.tsv", retry_versions)
    write_retry_versions_md(summary_dir / "retry_versions.md", retry_versions)
    write_retry_commands(summary_dir / "retry_commands.sh", workspace, retry_packages, run_context)
    write_retry_version_commands(summary_dir / "retry_versions.sh", workspace, retry_versions, run_context)
    write_retry_failed_step_commands(summary_dir / "retry_failed_steps.sh", workspace, retry_versions, run_context)
    write_retry_summary_md(summary_dir / "retry_summary.md", manifest, retry_packages, retry_versions)

    print(f"✅ run_manifest.md 已生成: {summary_dir / 'run_manifest.md'}")
    print(f"✅ all_packages_summary.md 已生成: {summary_dir / 'all_packages_summary.md'}")
    print(f"✅ root_cause_clusters.md 已生成: {summary_dir / 'root_cause_clusters.md'}")
    print(f"✅ auto_fix_overview.md 已生成: {summary_dir / 'auto_fix_overview.md'}")
    print(f"✅ analysis_summary_final.md 已生成: {summary_dir / 'analysis_summary_final.md'}")
    print(f"✅ retry_packages.txt 已生成: {summary_dir / 'retry_packages.txt'}")
    print(f"✅ retry_versions.md 已生成: {summary_dir / 'retry_versions.md'}")
    print(f"✅ retry_versions.sh 已生成: {summary_dir / 'retry_versions.sh'}")
    print(f"✅ retry_failed_steps.sh 已生成: {summary_dir / 'retry_failed_steps.sh'}")
    print(f"✅ retry_summary.md 已生成: {summary_dir / 'retry_summary.md'}")


if __name__ == "__main__":
    main()
